package com.hunts.bail.domain;

import java.util.List;

/**
 * Factory responsible for constructing valid BailRecord aggregates.
 *
 * OOD principles applied:
 *  - Factory Pattern (GoF Creational) : centralises BailRecord creation logic.
 *  - Single Responsibility : only creates BailRecords, does not validate or persist.
 *  - Open/Closed Principle : new record variations can be added without
 *    modifying the BailRecord constructor directly.
 */
public final class BailRecordFactory {

    /** Static utility class — not instantiable. */
    private BailRecordFactory() {}

    /**
     * Creates a new, ready-to-persist BailRecord aggregate.
     *
     * @param bailId        unique ID pre-generated by IDGeneratorService
     * @param accusedPerson the accused person entity
     * @param conditions    non-empty list of bail conditions
     * @param suretyInfo    surety details (may be empty string)
     * @return              a new BailRecord in ACTIVE status
     */
    public static BailRecord create(String bailId,
                                    AccusedPerson accusedPerson,
                                    List<BailCondition> conditions,
                                    String suretyInfo) {
        if (bailId == null || bailId.isBlank()) {
            throw new IllegalArgumentException("A bail ID is required to create a BailRecord.");
        }
        if (accusedPerson == null) {
            throw new IllegalArgumentException("An AccusedPerson is required.");
        }
        if (conditions == null || conditions.isEmpty()) {
            throw new IllegalArgumentException("At least one BailCondition is required.");
        }
        return new BailRecord(bailId, accusedPerson, conditions, suretyInfo);
    }
}
